// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GBCSfeb87POTDVLUaGrfg_1gJU4YPKA',
    appId: '1:946157853827:web:15e4846a00a6393930cfb6',
    messagingSenderId: '946157853827',
    projectId: 'padel-finder-palembang',
    authDomain: 'padel-finder-palembang.firebaseapp.com',
    storageBucket: 'padel-finder-palembang.firebasestorage.app',
    measurementId: 'G-B6CNZXCX46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2JndDI3OngiSC51xyebiW-oCSUjErRc',
    appId: '1:946157853827:android:f82696709289b01330cfb6',
    messagingSenderId: '946157853827',
    projectId: 'padel-finder-palembang',
    storageBucket: 'padel-finder-palembang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqM1gX5Mg-khVt6Vs7mJGekMNIDDyrU4',
    appId: '1:946157853827:ios:4342d655bc5775f630cfb6',
    messagingSenderId: '946157853827',
    projectId: 'padel-finder-palembang',
    storageBucket: 'padel-finder-palembang.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqM1gX5Mg-khVt6Vs7mJGekMNIDDyrU4',
    appId: '1:946157853827:ios:4342d655bc5775f630cfb6',
    messagingSenderId: '946157853827',
    projectId: 'padel-finder-palembang',
    storageBucket: 'padel-finder-palembang.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GBCSfeb87POTDVLUaGrfg_1gJU4YPKA',
    appId: '1:946157853827:web:5306f36d5c3e926730cfb6',
    messagingSenderId: '946157853827',
    projectId: 'padel-finder-palembang',
    authDomain: 'padel-finder-palembang.firebaseapp.com',
    storageBucket: 'padel-finder-palembang.firebasestorage.app',
    measurementId: 'G-HKTRXGBE8C',
  );
}
